/*------------------------------------------------------
 *
 *  decrypt.c
 *  LyreBird
 *
 *  Created by Armour on 16/09/2015
 *  Copyright (c) 2015 Armour. All rights reserved.
 *
 *------------------------------------------------------
 */

#include "decrypt.h"

/*
 * Function: base41_ctoi
 * -------------------
 *   Translate each of the group of 6 characters into cipher number
 *
 *   Parameters:
 *     tweet: the tweet which contained the group of 6 characters
 *     pos: the position of group in tweet
 *
 *   Returns:
 *      cipher number that generated by a group of 6 characters
 */

unsigned long long base41_ctoi(char *tweet, int pos) {
    unsigned long long ans = 0;
    int i;
    for (i = 0; i < 6; ++i) {
        ans += table_ctoi[(int)tweet[pos + i]] * pow(41, 5);
    }
    return ans;
}

/*
 * Function: base41_itoc
 * -------------------
 *   Translate plain-text number into new group of 6 characters
 *
 *   Parameters:
 *     number: the plain text which need to translate
 *
 *   Returns:
 *      a group of characters which were translated from plain-text number
 */

char *base41_itoc(unsigned long long number) {
    int i;
    char *group_char;
    group_char = (char *)malloc(sizeof(char) * CONSTANT_MULTIPLE);
    for (i = CONSTANT_MULTIPLE - 1; i >= 0; --i) {
        group_char[CONSTANT_MULTIPLE - i] = table_itoc[(int)(number / pow(POW_EXPONENT, i))];
        number /= pow(41, i);
    }
    return group_char;
}

